import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../..");
const appendixPath = resolve(repoRoot, "docs/run-bundle.appendix.md");

const factoryStageSchema = z.enum(["intent", "planning", "execution", "review", "release"]);

const factoryRunStatusSchema = z.enum([
  "created",
  "running",
  "cancelling",
  "cancelled",
  "orphaned",
  "blocked",
  "repairing",
  "ready-to-release",
  "completed"
]);

const stageArtifactRefSchema = z
  .object({
    stage: factoryStageSchema,
    kind: z.string().min(1),
    uri: z.string().min(1),
    sha256: z.string().optional(),
    description: z.string().optional()
  })
  .strict();

const stageRecordSchema = z
  .object({
    stage: factoryStageSchema,
    status: z.enum(["pending", "running", "passed", "failed", "skipped"]),
    startedAt: z.string().optional(),
    completedAt: z.string().optional(),
    artifacts: z.array(stageArtifactRefSchema).readonly()
  })
  .strict();

const factoryRunManifestSchema = z
  .object({
    runId: z.string().min(1),
    intentId: z.string().min(1),
    status: factoryRunStatusSchema,
    createdAt: z.string().min(1),
    stages: z.array(stageRecordSchema).readonly()
  })
  .strict();

const schemaEntries = {
  FactoryRunManifestSchema: factoryRunManifestSchema,
  FactoryRunStatusSchema: factoryRunStatusSchema,
  FactoryStageSchema: factoryStageSchema,
  StageArtifactRefSchema: stageArtifactRefSchema,
  StageRecordSchema: stageRecordSchema
} as const;

const header =
  "<!-- AUTOGENERATED by pnpm --filter @protostar/artifacts gen:schema-appendix; do not edit by hand -->\n\n";

const sections = Object.entries(schemaEntries)
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([schemaName, schema]) => {
    const jsonSchema = zodToJsonSchema(schema, schemaName);
    return `## ${schemaName}\n\n\`\`\`json\n${JSON.stringify(jsonSchema, null, 2)}\n\`\`\`\n`;
  });

await mkdir(dirname(appendixPath), { recursive: true });
await writeFile(appendixPath, `${header}${sections.join("\n")}\n`);
