// Plan 06a: source-of-truth for both promotion-side and admission-decision-artifact contracts
// is now @protostar/intent. This file is a backward-compat re-export barrel that preserves
// every name @protostar/policy ever exposed.

export {
  CAPABILITY_ENVELOPE_BUDGET_LIMIT_VIOLATION_CODES,
  CAPABILITY_ENVELOPE_EXECUTE_GRANT_VIOLATION_CODES,
  CAPABILITY_ENVELOPE_TOOL_PERMISSION_VIOLATION_CODES,
  CAPABILITY_ENVELOPE_WRITE_GRANT_VIOLATION_CODES,
  DUPLICATE_ACCEPTANCE_CRITERION_POLICY_CODE,
  INTENT_ARCHETYPE_PROPOSAL_LOW_CONFIDENCE_THRESHOLD,
  LOW_CONFIDENCE_GOAL_ARCHETYPE_POLICY_CODE,
  MANUAL_UNJUSTIFIED_ACCEPTANCE_CRITERION_POLICY_CODE,
  REPO_SCOPE_ADMISSION_REASON_CODES
} from "@protostar/intent";

export type {
  AdmitBugfixCapabilityEnvelopeInput,
  AdmitBugfixCapabilityEnvelopeResult,
  AdmitCosmeticTweakCapabilityEnvelopeInput,
  AdmitCosmeticTweakCapabilityEnvelopeResult,
  AdmitFeatureAddCapabilityEnvelopeInput,
  AdmitFeatureAddCapabilityEnvelopeResult,
  AdmitRefactorCapabilityEnvelopeInput,
  AdmitRefactorCapabilityEnvelopeResult,
  BugfixCapabilityEnvelopeUnsupportedDecision,
  CapabilityEnvelopeBudgetCapKey,
  CapabilityEnvelopeBudgetLimitViolation,
  CapabilityEnvelopeBudgetLimitViolationCode,
  CapabilityEnvelopeBudgetOverage,
  CapabilityEnvelopeExecuteGrantOverage,
  CapabilityEnvelopeExecuteGrantViolation,
  CapabilityEnvelopeExecuteGrantViolationCode,
  CapabilityEnvelopeOverageBase,
  CapabilityEnvelopeOverageDetection,
  CapabilityEnvelopeOverageFinding,
  CapabilityEnvelopeOverageKind,
  CapabilityEnvelopeRepoScopeOverage,
  CapabilityEnvelopeToolPermissionOverage,
  CapabilityEnvelopeToolPermissionViolation,
  CapabilityEnvelopeToolPermissionViolationCode,
  CapabilityEnvelopeWriteGrantViolation,
  CapabilityEnvelopeWriteGrantViolationCode,
  CosmeticTweakCapabilityEnvelopeGrant,
  DetectCapabilityEnvelopeOveragesInput,
  EvaluateRepoScopeAdmissionInput,
  FeatureAddCapabilityEnvelopeUnsupportedDecision,
  IntentAdmissionAcceptanceCriterionReference,
  IntentAdmissionHardZeroDimensionId,
  IntentAdmissionHardZeroReason,
  IntentAdmissionHardZeroReasonSource,
  IntentAdmissionIssueCode,
  IntentAdmissionIssueReference,
  IntentAdmissionMissingFieldDetection,
  IntentAdmissionMissingFieldDetectionSource,
  IntentAdmissionOutputContractSections,
  IntentAdmissionPolicyFinding,
  IntentAdmissionPolicyFindingCode,
  IntentAdmissionRequiredClarification,
  IntentAdmissionRequiredClarificationSource,
  IntentAmbiguityAdmissionDecision,
  IntentPromotionFailureDetails,
  IntentPromotionFailureState,
  PromoteIntentDraftInput,
  PromoteIntentDraftResult,
  RefactorCapabilityEnvelopeUnsupportedDecision,
  RepoScopeAdmissionDecision,
  RepoScopeAdmissionReasonCode,
  RepoScopeAdmissionResult,
  RepoScopeAdmissionResultKind,
  RepoScopeAdmissionResultSeverity,
  RepoScopeAdmissionVerdict,
  RequiredIntentDraftDimensionCheck,
  RequiredIntentDraftFieldCheck,
  ValidateCapabilityEnvelopeBudgetLimitsInput,
  ValidateCapabilityEnvelopeBudgetLimitsResult,
  ValidateCapabilityEnvelopeExecuteGrantsInput,
  ValidateCapabilityEnvelopeExecuteGrantsResult,
  ValidateCapabilityEnvelopeRepoScopesInput,
  ValidateCapabilityEnvelopeToolPermissionsInput,
  ValidateCapabilityEnvelopeToolPermissionsResult,
  ValidateCapabilityEnvelopeWriteGrantsInput,
  ValidateCapabilityEnvelopeWriteGrantsResult,
  ValidateIntentDraftCapabilityEnvelopeAdmissionInput,
  ValidateIntentDraftCapabilityEnvelopeAdmissionResult
} from "@protostar/intent";

// Admission-decision-artifact concerns (Plan 06a Rule-4 deviation: also moved to intent).
export {
  ADMISSION_DECISION_ARTIFACT_NAME,
  ADMISSION_DECISION_OUTCOMES,
  ADMISSION_DECISION_SCHEMA_VERSION
} from "@protostar/intent";
export type {
  AdmissionDecisionAmbiguityDetail,
  AdmissionDecisionArtifactDetails,
  AdmissionDecisionArtifactPayload,
  AdmissionDecisionGateSummary,
  AdmissionDecisionOutcome,
  CreateAdmissionDecisionArtifactInput
} from "@protostar/intent";
